SHIFT_NOTE_INT = 9

PAD_1_NOTE_INT = 36
PAD_2_NOTE_INT = 37
PAD_3_NOTE_INT = 38
PAD_4_NOTE_INT = 39
PAD_5_NOTE_INT = 40
PAD_6_NOTE_INT = 41
PAD_7_NOTE_INT = 42
PAD_8_NOTE_INT = 43

PADS_NOTES = [
    PAD_1_NOTE_INT,
    PAD_2_NOTE_INT,
    PAD_3_NOTE_INT,
    PAD_4_NOTE_INT,
    PAD_5_NOTE_INT,
    PAD_6_NOTE_INT,
    PAD_7_NOTE_INT,
    PAD_8_NOTE_INT,
]

FX1_1_ACTIVATE_NOTE_INT = 48
FX1_2_ACTIVATE_NOTE_INT = 50
FX1_3_ACTIVATE_NOTE_INT = 52
FX2_1_ACTIVATE_NOTE_INT = 69
FX2_2_ACTIVATE_NOTE_INT = 71
FX2_3_ACTIVATE_NOTE_INT = 72

FX_ACTIVATE_NOTES = [
    FX1_1_ACTIVATE_NOTE_INT,
    FX1_2_ACTIVATE_NOTE_INT,
    FX1_3_ACTIVATE_NOTE_INT,
    FX2_1_ACTIVATE_NOTE_INT,
    FX2_2_ACTIVATE_NOTE_INT,
    FX2_3_ACTIVATE_NOTE_INT,
]

SEMITONE_DOWN_NOTE_INT = 49
SEMITONE_DOWN_NOTE = 0x31

SEMITONE_UP_NOTE_INT = 51
SEMITONE_UP_NOTE = 0x33

KNOB_1_1_CONTROL_INT = 74
KNOB_1_2_CONTROL_INT = 71
KNOB_1_3_CONTROL_INT = 76
KNOB_2_1_CONTROL_INT = 93
KNOB_2_2_CONTROL_INT = 18
KNOB_2_3_CONTROL_INT = 19

KNOBS_CONTROLS = [
    KNOB_1_1_CONTROL_INT,
    KNOB_1_2_CONTROL_INT,
    KNOB_1_3_CONTROL_INT,
    KNOB_2_1_CONTROL_INT,
    KNOB_2_2_CONTROL_INT,
    KNOB_2_3_CONTROL_INT,
]

SAMPLE_1_NOTE_INT = 53
SAMPLE_2_NOTE_INT = 54
SAMPLE_3_NOTE_INT = 55
SAMPLE_4_NOTE_INT = 56
SAMPLE_5_NOTE_INT = 57
SAMPLE_6_NOTE_INT = 58
SAMPLE_7_NOTE_INT = 59
SAMPLE_8_NOTE_INT = 60
SAMPLE_9_NOTE_INT = 61
SAMPLE_10_NOTE_INT = 62
SAMPLE_11_NOTE_INT = 63
SAMPLE_12_NOTE_INT = 64
SAMPLE_13_NOTE_INT = 65
SAMPLE_14_NOTE_INT = 66
SAMPLE_15_NOTE_INT = 67
SAMPLE_16_NOTE_INT = 68

SAMPLES_NOTES = [
    SAMPLE_1_NOTE_INT,
    SAMPLE_2_NOTE_INT,
    SAMPLE_3_NOTE_INT,
    SAMPLE_4_NOTE_INT,
    SAMPLE_5_NOTE_INT,
    SAMPLE_6_NOTE_INT,
    SAMPLE_7_NOTE_INT,
    SAMPLE_8_NOTE_INT,
    SAMPLE_9_NOTE_INT,
    SAMPLE_10_NOTE_INT,
    SAMPLE_11_NOTE_INT,
    SAMPLE_12_NOTE_INT,
    SAMPLE_13_NOTE_INT,
    SAMPLE_14_NOTE_INT,
    SAMPLE_15_NOTE_INT,
    SAMPLE_16_NOTE_INT,
]
